# Remove this line and rename to: config.yaml
# This is a user editable config file.
certificates:
  subdomain: "example"
  domain: "contoso.com"
  fqdn: "example.contoso.com"
  root_dir: "/root/.acme.sh"
  domain_dir: "/root/.acme.sh/contoso.com_ecc/contoso.com_ecc"
  subdomain_dir: "/root/.acme.sh"
directories:
  install_dir: "$INSTALL_DIR"
  source_apps: "$BASE_DIR"

